/**
 * @file TChBurntBlend.h
 * @author F.J. Arnau <farnau@mot.upv.es>
 * @version 0.1.0
 *
 * @section LICENSE
 *
 * This file is part of OpenWAM.
 *
 * OpenWAM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenWAM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenWAM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @section DESCRIPTION
 * The TChBurntGasoil class represents the chemical component burnt gas produced by a
 * combustion with a fuel blend.
 *
 * This class include different method to determine the chemical and
 * thermodynamics properties of a burnt gas.
 *
 */

//#include "stdafx.h"
#include "TChemicalComponent.h"
#include "TChBurntGasoil.h"
#include "TChBurntGasolina.h"
#include <string>

#ifndef __TCHBURNTBLEND_H
#define __TCHBURNTBLEND_H

/*!
 * \class	TChBurntBlend
 *
 * \brief	Chemical component: Burnt gas by a fuel blend.
 *
 * \author	F.J. Arnau (farnau@mot.upv.es)
 * \date	07/12/2015
 */

class TChBurntBlend: public TChemicalComponent {
  private:

	TComponentArray_obj _BurntGas;	//!< The vector for the burnt gasses generated by the different fuels.
	std::vector<double> _Yq_BLEND;//!< The mass fraction for the different burnt gasses.

  public:

	/*!
	 * \fn	TChBurntBlend(std::string nombre, std::vector<TChemicalComponent *> Fuel,
	 * 		std::vector<double> Fraction, std::vector < double > PMQ, double RU, double XO2);
	 *
	 * \brief	Constructor.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 *
	 * \param	nombre			The name of the chemical component.
	 * \param [in,out]	Fuel	The vector for the different fuels that composes the blend.
	 * \param	Fraction		The mass fraction of the different fuels [-].
	 * \param	PMQ				The molecular weight of the different burnt gasses [gr / mol].
	 * \param	RU				The universal gas constant [J / (kg K)].
	 * \param	XO2				The oxygen molar fraction in the air [-].
	 */

	TChBurntBlend(std::string nombre, TComponentArray_obj Fuel, std::vector<double> Fraction, std::vector <
				  double > PMQ, double RU, double XO2);

	/*!
	 * \fn	~TChBurntBlend();
	 *
	 * \brief	Destructor.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 */

	~TChBurntBlend();

	/*!
	 * \fn	double FunCp(double T);
	 *
	 * \brief	Function for C_p.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 *
	 * \param	T	Temperature [K].
	 *
	 * \return	Specific heat C_p [J / (kg K)].
	 */

	virtual double FunCp(double T);

	/*!
	 * \fn	double FunCv(double T);
	 *
	 * \brief	Function for C_v.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 *
	 * \param	T	Temperature [K].
	 *
	 * \return	Specific heat C_v [J / (kg K.)]
	 */

	virtual double FunCv(double T);

	/*!
	 * \fn	double FunU(double T);
	 *
	 * \brief	Function for internal energy.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 *
	 * \param	T	Temperature [K].
	 *
	 * \return	Internal energy [J / kg].
	 */

	virtual double FunU(double T);

	/*!
	 * \fn	double FunH(double T);
	 *
	 * \brief	Function for the enthalpy.
	 *
	 * \author	F.J. Arnau (farnau@mot.upv.es)
	 * \date	07/12/2015
	 *
	 * \param	T	Temperature [K].
	 *
	 * \return	Enthalpy [J / kg].
	 */

	virtual double FunH(double T);

};

#endif
