#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_BUILD 0
#define VERSION_QFE 6
#define VERSION_BUILD_DATE "25/05/2019"
#define VERSION_BUILD_TIME "08:00:00UTC"

#define _STR(x) #x
#define STR(x) _STR(x)

#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_QFE
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_BUILD) "." STR(VERSION_QFE)
#define VERSION_PRINT "v" STR(VERSION_MAJOR) "." STR(VERSION_MINOR) " build " STR(VERSION_BUILD)
#define VERSION_COMPANY ""
#define VERSION_COPYRIGHT "(C)CMT-Motores Termicos (UPV) 2016"
#define VERSION_TRADEMARK ""
#define VERSION_BUILD_DATE_TIME VERSION_BUILD_DATE " - " VERSION_BUILD_TIME
